/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f439zi.h"
#include "stm32f439zi_gpio_driver.h"

int main(void)
{
	//1- setup the GPIO clock
	GPIO_PeriClockControl(GPIOB, ENABLE);
	GPIO_PeriClockControl(GPIOC, ENABLE);

	//2- Set the GPIOx pin to output mode GPIOx_MODER and  Set the GPIOx pin output type to push-pull GPIOx_OTYPER

	GPIO_Handle_t GPIOB_LED;

	GPIOB_LED.pGPIOx 								= GPIOB;
	GPIOB_LED.GPIO_PinConfig.GPIO_PinMode 			= GPIO_MODE_OUTPUT;
	GPIOB_LED.GPIO_PinConfig.GPIO_PinNumber 		= 7;
	GPIOB_LED.GPIO_PinConfig.GPIO_PinOPType 		= GPIO_OP_TYPE_PP;		//Push Pull output type
	GPIOB_LED.GPIO_PinConfig.GPIO_PinPuPdControl 	= GPIO_NO_PUPD;
	GPIOB_LED.GPIO_PinConfig.GPIO_PinSpeed 			= GPIO_SPEED_FAST;

	//3- Set GPIOC port pin 13 to input

	GPIO_Handle_t GPIOC_Button;

	GPIOC_Button.pGPIOx 							= GPIOC;
	GPIOC_Button.GPIO_PinConfig.GPIO_PinMode		= GPIO_MODE_INPUT;
	GPIOC_Button.GPIO_PinConfig.GPIO_PinNumber		= 13;
	GPIOC_Button.GPIO_PinConfig.GPIO_PinPuPdControl	= GPIO_PIN_PD;
	GPIOC_Button.GPIO_PinConfig.GPIO_PinSpeed		= GPIO_SPEED_FAST;


	GPIO_Init(&GPIOB_LED);
	GPIO_Init(&GPIOC_Button);

    /* Loop forever */
	while(1)
	{
		if(GPIO_ReadFromInputPin(GPIOC, 13) == ENABLE)
		{
			for(uint32_t i = 0; i < 500000/2; i++)
			{

			}
			GPIO_ToggleOutputPin(GPIOB, 7);
		}

	}
}
